In [55]:
import kagglehub as kh
from kagglehub import KaggleDatasetAdapter

df = kh.load_dataset(KaggleDatasetAdapter.PANDAS, "ryanholbrook/dl-course-data", "abalone.csv")
df.head(10)

/tmp/ipykernel_4186/3643711923.py:4: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df = kh.load_dataset(KaggleDatasetAdapter.PANDAS, "ryanholbrook/dl-course-data", "abalone.csv")

,Type,LongestShell,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7
5,I,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.120,8
6,F,0.530,0.415,0.150,0.7775,0.2370,0.1415,0.330,20
7,F,0.545,0.425,0.125,0.7680,0.2940,0.1495,0.260,16
8,M,0.475,0.370,0.125,0.5095,0.2165,0.1125,0.165,9
9,F,0.550,0.440,0.150,0.8945,0.3145,0.1510,0.320,19

In [56]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Type           4177 non-null   object
 1   LongestShell   4177 non-null   float64
 2   Diameter       4177 non-null   float64
 3   Height         4177 non-null   float64
 4   WholeWeight    4177 non-null   float64
 5   ShuckedWeight  4177 non-null   float64
 6   VisceraWeight  4177 non-null   float64
 7   ShellWeight    4177 non-null   float64
 8   Rings          4177 non-null   int64
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB

In [58]:
df['Type'].head(10)

0    M
1    M
2    F
3    M
4    I
5    I
6    F
7    F
8    M
9    F
Name: Type, dtype: object

In [59]:
df = df[df['Type'] != "I"]
ohe = OneHotEncoder(sparse_output = False)
encoded_type = ohe.fit_transform(df[['Type']])
encoded_df = pd.DataFrame(encoded_type, columns = ohe.get_feature_names_out(['Type']))
df = pd.concat([df, encoded_df], axis = 1)
df.head(10)

,Type,LongestShell,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings,Type_F,Type_M
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15.0,0.0,1.0
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7.0,0.0,1.0
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9.0,1.0,0.0
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10.0,0.0,1.0
6,F,0.530,0.415,0.150,0.7775,0.2370,0.1415,0.330,20.0,0.0,1.0
7,F,0.545,0.425,0.125,0.7680,0.2940,0.1495,0.260,16.0,1.0,0.0
8,M,0.475,0.370,0.125,0.5095,0.2165,0.1125,0.165,9.0,1.0,0.0
9,F,0.550,0.440,0.150,0.8945,0.3145,0.1510,0.320,19.0,0.0,1.0
10,F,0.525,0.380,0.140,0.6065,0.1940,0.1475,0.210,14.0,0.0,1.0
11,M,0.430,0.350,0.110,0.4060,0.1675,0.0810,0.135,10.0,1.0,0.0

In [60]:
df = df.drop('Type', axis = 'columns')
df.head(10)

,LongestShell,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings,Type_F,Type_M
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15.0,0.0,1.0
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7.0,0.0,1.0
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9.0,1.0,0.0
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10.0,0.0,1.0
6,0.530,0.415,0.150,0.7775,0.2370,0.1415,0.330,20.0,0.0,1.0
7,0.545,0.425,0.125,0.7680,0.2940,0.1495,0.260,16.0,1.0,0.0
8,0.475,0.370,0.125,0.5095,0.2165,0.1125,0.165,9.0,1.0,0.0
9,0.550,0.440,0.150,0.8945,0.3145,0.1510,0.320,19.0,0.0,1.0
10,0.525,0.380,0.140,0.6065,0.1940,0.1475,0.210,14.0,0.0,1.0
11,0.430,0.350,0.110,0.4060,0.1675,0.0810,0.135,10.0,1.0,0.0

In [62]:
temp_df = df[['Rings', 'Type_F', 'Type_M']]
temp_df.head()

   Rings  Type_F  Type_M
0   15.0     0.0     1.0
1    7.0     0.0     1.0
2    9.0     1.0     0.0
3   10.0     0.0     1.0
6   20.0     0.0     1.0

In [ ]:
fig, axes = plt.figure(figsize = (1, 2))

axes[0].plot(temp_df['Type_M'], df[''])